import '../models/notification_model.dart';
import '../../const/app_assets.dart';

class NotificationRepository {
  Future<List<NotificationModel>> getNotifications() async {
    return const [
      NotificationModel(
        id: 'n1',
        title: 'The Morning Rush is live now!',
        body: 'DJ Ace is on air. Tune in and start your morning right.',
        timeAgo: '10:30 AM',
        timeGroup: 'Today',
        isRead: false,
        type: 'mic',
        imageUrl: AppAssets.show1,
        hasAction: true,
      ),
      NotificationModel(
        id: 'n2',
        title: 'New Show Alert!',
        body: '"Afternoon Vibes" with Mariam airs today at 10:00 AM.',
        timeAgo: '9:15 AM',
        timeGroup: 'Today',
        isRead: false,
        type: 'calendar',
        imageUrl: AppAssets.show2,
        hasAction: true,
      ),
      NotificationModel(
        id: 'n3',
        title: 'Add a Show to Favourites',
        body: 'Tap to save your favorite shows and never miss them.',
        timeAgo: '8:45 AM',
        timeGroup: 'Today',
        isRead: false,
        type: 'favourite',
        imageUrl: '',
        hasAction: true,
      ),
      NotificationModel(
        id: 'n4',
        title: 'New Music Added',
        body: 'Burna Boy - Update is now in rotation on 93.5 AREA FM.',
        timeAgo: 'Yesterday, 6:45 PM',
        timeGroup: 'Yesterday',
        isRead: false,
        type: 'music',
        imageUrl: AppAssets.show3,
        hasAction: true,
      ),
      NotificationModel(
        id: 'n5',
        title: 'Event Reminder',
        body: 'Praise in the City 2025 is coming up on Dec 26! Get your tickets now.',
        timeAgo: 'Yesterday, 2:00 PM',
        timeGroup: 'Yesterday',
        isRead: false,
        type: 'event',
        imageUrl: AppAssets.banner,
        hasAction: true,
      ),
      NotificationModel(
        id: 'n6',
        title: 'Notification Settings',
        body: 'Manage what you want to stay updated on from 93.5 AREA FM.',
        timeAgo: 'Yesterday, 10:30 AM',
        timeGroup: 'Yesterday',
        isRead: true,
        type: 'settings',
        imageUrl: '',
        hasAction: true,
      ),
      NotificationModel(
        id: 'n7',
        title: 'Podcast Update',
        body: 'A new episode of "Drive Time Podcast" is out now.',
        timeAgo: 'May 5, 11:20 AM',
        timeGroup: 'This Week',
        isRead: true,
        type: 'podcast',
        imageUrl: AppAssets.show4,
        hasAction: true,
      ),
      // ── MENTIONS ──────────────────────────────────────────────────
      NotificationModel(
        id: 'm1',
        title: 'DJ Ace mentioned you',
        body: 'Big P, thanks for supporting the show this morning! 🙌',
        timeAgo: '10:30 AM',
        timeGroup: 'Today',
        isRead: false,
        type: 'mention',
        avatarUrl: AppAssets.show1,
        imageUrl: AppAssets.show1,
        isMention: true,
      ),
      NotificationModel(
        id: 'm2',
        title: 'Mariam mentioned you',
        body: '@Big P don\'t miss "Afternoon Vibes" today at 10AM. We\'ve got something special! 🎧',
        timeAgo: '9:15 AM',
        timeGroup: 'Today',
        isRead: false,
        type: 'mention',
        avatarUrl: AppAssets.show2,
        imageUrl: AppAssets.show2,
        isMention: true,
      ),
      NotificationModel(
        id: 'm3',
        title: '93.5 AREA FM mentioned you',
        body: 'Shoutout to @Big P for being part of the 93.5 AREA FM family! 🙌',
        timeAgo: '8:45 AM',
        timeGroup: 'Today',
        isRead: false,
        type: 'mention',
        avatarUrl: AppAssets.logo,
        imageUrl: AppAssets.logo,
        isMention: true,
      ),
      NotificationModel(
        id: 'm4',
        title: 'Drive Time Podcast mentioned you',
        body: '@Big P Episode 12 is out now! Tap in and let us know what you think.',
        timeAgo: 'Yesterday, 6:45 PM',
        timeGroup: 'Yesterday',
        isRead: false,
        type: 'mention',
        avatarUrl: AppAssets.show3,
        imageUrl: AppAssets.show3,
        isMention: true,
      ),
      NotificationModel(
        id: 'm5',
        title: '99 Problems mentioned you',
        body: '@Big P You\'ve got to hear this one! New episode dropping soon. 🔥',
        timeAgo: 'Yesterday, 2:00 PM',
        timeGroup: 'Yesterday',
        isRead: false,
        type: 'mention',
        avatarUrl: AppAssets.show4,
        imageUrl: AppAssets.show4,
        isMention: true,
      ),
      NotificationModel(
        id: 'm6',
        title: 'Praise in the City mentioned you',
        body: '@Big P We can\'t wait to see you at PITC 2025! Let\'s make it unforgettable. 🙌',
        timeAgo: 'Yesterday, 10:30 AM',
        timeGroup: 'Yesterday',
        isRead: true,
        type: 'mention',
        avatarUrl: AppAssets.banner,
        imageUrl: AppAssets.banner,
        isMention: true,
      ),
      NotificationModel(
        id: 'm7',
        title: 'Burna Boy mentioned you',
        body: '@Big P Appreciate the love and support! More good music coming your way. 🔥',
        timeAgo: 'May 5, 11:20 AM',
        timeGroup: 'This Week',
        isRead: true,
        type: 'mention',
        avatarUrl: AppAssets.show1,
        imageUrl: AppAssets.show1,
        isMention: true,
      ),
    ];
  }
}
