import '../models/notification_model.dart';
import '../../const/app_assets.dart';

class NotificationRepository {
  Future<List<NotificationModel>> getNotifications() async {
    return const [
      NotificationModel(
        id: 'n1',
        title: 'The Morning Rush is live now!',
        body: 'DJ Ace is on air. Tune in and start your morning right.',
        timeAgo: '10:30 AM',
        timeGroup: 'Today',
        isRead: false,
        type: 'mic',
        imageUrl: AppAssets.show1,
        hasAction: true,
      ),
      NotificationModel(
        id: 'n2',
        title: 'New Show Alert!',
        body: '"Afternoon Vibes" with Mariam airs today at 10:00 AM.',
        timeAgo: '9:15 AM',
        timeGroup: 'Today',
        isRead: false,
        type: 'calendar',
        imageUrl: AppAssets.show2,
        hasAction: true,
      ),
      NotificationModel(
        id: 'n3',
        title: 'Add a Show to Favourites',
        body: 'Tap to save your favorite shows and never miss them.',
        timeAgo: '8:45 AM',
        timeGroup: 'Today',
        isRead: false,
        type: 'favourite',
        imageUrl: '',
        hasAction: true,
      ),
      NotificationModel(
        id: 'n4',
        title: 'New Music Added',
        body: 'Burna Boy - Update is now in rotation on 93.5 AREA FM.',
        timeAgo: 'Yesterday, 6:45 PM',
        timeGroup: 'Yesterday',
        isRead: false,
        type: 'music',
        imageUrl: AppAssets.show3,
        hasAction: true,
      ),
      NotificationModel(
        id: 'n5',
        title: 'Event Reminder',
        body: 'Praise in the City 2025 is coming up on Dec 26! Get your tickets now.',
        timeAgo: 'Yesterday, 2:00 PM',
        timeGroup: 'Yesterday',
        isRead: false,
        type: 'event',
        imageUrl: AppAssets.banner,
        hasAction: true,
      ),
      NotificationModel(
        id: 'n6',
        title: 'Notification Settings',
        body: 'Manage what you want to stay updated on from 93.5 AREA FM.',
        timeAgo: 'Yesterday, 10:30 AM',
        timeGroup: 'Yesterday',
        isRead: true,
        type: 'settings',
        imageUrl: '',
        hasAction: true,
      ),
      NotificationModel(
        id: 'n7',
        title: 'Podcast Update',
        body: 'A new episode of "Drive Time Podcast" is out now.',
        timeAgo: 'May 5, 11:20 AM',
        timeGroup: 'This Week',
        isRead: true,
        type: 'podcast',
        imageUrl: AppAssets.show4,
        hasAction: true,
      ),
    ];
  }
}
