import 'package:flutter/material.dart';
import '../models/presenter_model.dart';

class PresenterRepository {
  Future<List<PresenterModel>> getPresenters() async {
    return const [
      PresenterModel(
        id: 'pres_big_p',
        name: 'Big P',
        showName: 'Big P in the City',
        timeSlot: '6:00 AM - 10:00 AM',
        category: 'Presenters',
        isOnAir: true,
        image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
        bio: 'Top urban presenter and radio personality bringing city vibes, hot trends, and unmatched energy to your sunrise.',
        instagram: 'https://instagram.com/bigp_areafm',
        twitter: 'https://twitter.com/bigp_areafm',
        tiktok: 'https://tiktok.com/@bigp_areafm',
        gradientColors: [Color(0xFFD35400), Color(0xFF6E2200)],
        accentColor: Color(0xFFFF6A00),
      ),
      PresenterModel(
        id: 'pres_dj_ace',
        name: 'DJ Ace',
        showName: 'Drive Time',
        timeSlot: '3:00 PM - 7:00 PM',
        category: 'DJs',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
        bio: 'Master of the turntable mixing seamless transitions and rush hour beats every afternoon.',
        instagram: 'https://instagram.com/djace',
        twitter: 'https://twitter.com/djace',
        tiktok: 'https://tiktok.com/@djace',
        gradientColors: [Color(0xFF0F3E9B), Color(0xFF061840)],
        accentColor: Color(0xFF38BDF8),
      ),
      PresenterModel(
        id: 'pres_tolu',
        name: 'Tolu',
        showName: 'Afternoon Vibes',
        timeSlot: '10:00 AM - 3:00 PM',
        category: 'Presenters',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
        bio: 'Smooth talking host diving into lifestyle, celebrity culture, and midday musical therapy.',
        instagram: 'https://instagram.com/tolu_area',
        twitter: 'https://twitter.com/tolu_area',
        tiktok: 'https://tiktok.com/@tolu_area',
        gradientColors: [Color(0xFF8D4012), Color(0xFF381604)],
        accentColor: Color(0xFFFF8A00),
      ),
      PresenterModel(
        id: 'pres_dj_switch',
        name: 'DJ Switch',
        showName: 'Area Nights',
        timeSlot: '7:00 PM - 12:00 AM',
        category: 'DJs',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
        bio: 'Nighttime frequency pilot delivering underground rhythms, live mixes, and late night soundscapes.',
        instagram: 'https://instagram.com/djswitch',
        twitter: 'https://twitter.com/djswitch',
        tiktok: 'https://tiktok.com/@djswitch',
        gradientColors: [Color(0xFF10284D), Color(0xFF091220)],
        accentColor: Color(0xFF60A5FA),
      ),
      PresenterModel(
        id: 'pres_lami',
        name: 'Lami',
        showName: 'Night Cap',
        timeSlot: '12:00 AM - 2:00 AM',
        category: 'Presenters',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&w=600&q=80',
        bio: 'Intimate late-night talk, soulful melodies, and honest conversations as the city sleeps.',
        instagram: 'https://instagram.com/lami_fm',
        twitter: 'https://twitter.com/lami_fm',
        tiktok: 'https://tiktok.com/@lami_fm',
        gradientColors: [Color(0xFFD64B00), Color(0xFF6B1E00)],
        accentColor: Color(0xFFFF7A1A),
      ),
      PresenterModel(
        id: 'pres_chef_k',
        name: 'Chef K',
        showName: 'Weekend Vibes',
        timeSlot: 'Sat - Sun 12:00 PM',
        category: 'Presenters',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
        bio: 'Cooking up the best weekend playlist, culinary talk, and party anthems across the region.',
        instagram: 'https://instagram.com/chefk',
        twitter: 'https://twitter.com/chefk',
        tiktok: 'https://tiktok.com/@chefk',
        gradientColors: [Color(0xFF12345E), Color(0xFF09172A)],
        accentColor: Color(0xFF38BDF8),
      ),
      PresenterModel(
        id: 'pres_jayda',
        name: 'Jayda',
        showName: 'News Anchor',
        timeSlot: 'Weekdays',
        category: 'News Team',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=600&q=80',
        bio: 'Fast, verified, and authoritative news bulletins keeping listeners informed every top of the hour.',
        instagram: 'https://instagram.com/jayda_news',
        twitter: 'https://twitter.com/jayda_news',
        tiktok: 'https://tiktok.com/@jayda_news',
        gradientColors: [Color(0xFFB54700), Color(0xFF4A1800)],
        accentColor: Color(0xFFFF8A00),
      ),
      PresenterModel(
        id: 'pres_eddie',
        name: 'Eddie',
        showName: 'Producer',
        timeSlot: 'Behind the Scenes',
        category: 'Producers',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
        bio: 'Master audio engineer and broadcast architect producing prime-time flagship shows.',
        instagram: 'https://instagram.com/eddie_producer',
        twitter: 'https://twitter.com/eddie_producer',
        tiktok: 'https://tiktok.com/@eddie_producer',
        gradientColors: [Color(0xFF132F52), Color(0xFF0A1524)],
        accentColor: Color(0xFF60A5FA),
      ),
      PresenterModel(
        id: 'pres_bella',
        name: 'Bella',
        showName: 'Content Creator',
        timeSlot: 'Digital Team',
        category: 'Producers',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        bio: 'Digital storytelling wizard turning radio moments into viral social content and podcasts.',
        instagram: 'https://instagram.com/bella_digital',
        twitter: 'https://twitter.com/bella_digital',
        tiktok: 'https://tiktok.com/@bella_digital',
        gradientColors: [Color(0xFFB84E10), Color(0xFF4C1D04)],
        accentColor: Color(0xFFFF7A1A),
      ),
    ];
  }

  Future<PresenterModel> getPresenterById(String id) async {
    final presenters = await getPresenters();
    return presenters.firstWhere((p) => p.id == id, orElse: () => presenters.first);
  }
}
