import 'package:flutter/material.dart';
import '../models/presenter_model.dart';

class PresenterRepository {
  Future<List<PresenterModel>> getPresenters() async {
    return const [
      PresenterModel(
        id: 'pres_big_p',
        name: 'Big P',
        showName: 'Big P in the City',
        timeSlot: '6:00 AM - 10:00 AM',
        days: 'Weekdays',
        category: 'Presenters',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?auto=format&fit=crop&w=500&q=80',
        tagline: 'Waking up Lagos with the best music, good vibes and real talk every weekday morning.',
        about: 'Big P is one of Lagos\' most loved on-air personalities. He brings the perfect blend of music, entertainment and street vibes to get your day started right. Real, relatable and always on point.',
        bio: 'Big P started his radio journey with a passion for music and a love for connecting with people. Over the years, he has become a household name, known for his energy, authenticity and impact.',
        birthday: 'May 20',
        onAirSince: '2016',
        location: 'Lagos, Nigeria',
        instagram: 'https://instagram.com/bigp_areafm',
        twitter: 'https://twitter.com/bigp_areafm',
        tiktok: 'https://tiktok.com/@bigp_areafm',
        gradientColors: [Color(0xFFD64B00), Color(0xFF8A2E00)],
        accentColor: Color(0xFFFF6A00),
      ),
      PresenterModel(
        id: 'pres_dj_ace',
        name: 'DJ Ace',
        showName: 'Drive Time',
        timeSlot: '3:00 PM - 7:00 PM',
        days: 'Weekdays',
        category: 'DJs',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=500&q=80',
        tagline: 'Cruising through the evening traffic with heavy beats and top tier mixes.',
        about: 'DJ Ace is the undisputed master of the turntable. Delivering seamless transitions, club bangers, and exclusive live sets during your evening rush.',
        bio: 'Starting from the underground club scene, DJ Ace rose through the ranks to anchor the biggest drive-time show in the city.',
        birthday: 'Aug 14',
        onAirSince: '2018',
        location: 'Lagos, Nigeria',
        instagram: 'https://instagram.com/djace',
        twitter: 'https://twitter.com/djace',
        tiktok: 'https://tiktok.com/@djace',
        gradientColors: [Color(0xFF0F3E9B), Color(0xFF061840)],
        accentColor: Color(0xFF38BDF8),
      ),
      PresenterModel(
        id: 'pres_tolu',
        name: 'Tolu',
        showName: 'Afternoon Vibes',
        timeSlot: '10:00 AM - 3:00 PM',
        days: 'Weekdays',
        category: 'Presenters',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=500&q=80',
        tagline: 'Your midday companion for lifestyle, trending gossip, and smooth Afrobeats.',
        about: 'Tolu brings charisma and warmth to the midday slot. She connects effortlessly with listeners on matters of love, career, and culture.',
        bio: 'With a background in mass communications and theatre arts, Tolu has hosted some of the most memorable celebrity interviews on radio.',
        birthday: 'Nov 03',
        onAirSince: '2019',
        location: 'Lagos, Nigeria',
        instagram: 'https://instagram.com/tolu_area',
        twitter: 'https://twitter.com/tolu_area',
        tiktok: 'https://tiktok.com/@tolu_area',
        gradientColors: [Color(0xFF8D4012), Color(0xFF381604)],
        accentColor: Color(0xFFFF8A00),
      ),
      PresenterModel(
        id: 'pres_dj_switch',
        name: 'DJ Switch',
        showName: 'Area Nights',
        timeSlot: '7:00 PM - 12:00 AM',
        days: 'Mon - Fri',
        category: 'DJs',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=500&q=80',
        tagline: 'Unleashing high octane nighttime beats and underground club soundscapes.',
        about: 'DJ Switch commands the night with high energy, futuristic transitions, and non-stop turntable wizardry.',
        bio: 'Award-winning turntablist and music producer pushing boundaries of Nigerian and global electronic beats.',
        birthday: 'Jan 22',
        onAirSince: '2017',
        location: 'Lagos, Nigeria',
        instagram: 'https://instagram.com/djswitch',
        twitter: 'https://twitter.com/djswitch',
        tiktok: 'https://tiktok.com/@djswitch',
        gradientColors: [Color(0xFF10284D), Color(0xFF091220)],
        accentColor: Color(0xFF60A5FA),
      ),
      PresenterModel(
        id: 'pres_lami',
        name: 'Lami',
        showName: 'Night Cap',
        timeSlot: '12:00 AM - 2:00 AM',
        days: 'Weeknights',
        category: 'Presenters',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=500&q=80',
        tagline: 'Soulful confessions, mellow R&B, and heartfelt late-night talks.',
        about: 'Lami is the late-night voice of solace and connection. Her soothing tone and deep questions make Night Cap a listener favourite.',
        bio: 'Psychology graduate turned broadcaster, Lami creates safe spaces for listeners to unwind after long metropolitan days.',
        birthday: 'Sep 11',
        onAirSince: '2020',
        location: 'Lagos, Nigeria',
        instagram: 'https://instagram.com/lami_fm',
        twitter: 'https://twitter.com/lami_fm',
        tiktok: 'https://tiktok.com/@lami_fm',
        gradientColors: [Color(0xFFD64B00), Color(0xFF6B1E00)],
        accentColor: Color(0xFFFF7A1A),
      ),
      PresenterModel(
        id: 'pres_chef_k',
        name: 'Chef K',
        showName: 'Weekend Vibes',
        timeSlot: '12:00 PM - 4:00 PM',
        days: 'Sat - Sun',
        category: 'Presenters',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?auto=format&fit=crop&w=500&q=80',
        tagline: 'Cooking up the finest weekend recipes, party anthems, and lifestyle tips.',
        about: 'Chef K blends culinary passion with radio finesse. He hosts the weekend prime spot, exploring food culture and the latest hit tracks.',
        bio: 'Professional chef and passionate radio host bridging the gap between foodies and music lovers across the airwaves.',
        birthday: 'Jul 08',
        onAirSince: '2021',
        location: 'Lagos, Nigeria',
        instagram: 'https://instagram.com/chefk',
        twitter: 'https://twitter.com/chefk',
        tiktok: 'https://tiktok.com/@chefk',
        gradientColors: [Color(0xFF12345E), Color(0xFF09172A)],
        accentColor: Color(0xFF38BDF8),
      ),
      PresenterModel(
        id: 'pres_jayda',
        name: 'Jayda',
        showName: 'News Anchor',
        timeSlot: 'Hourly News',
        days: 'Weekdays',
        category: 'News Team',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=500&q=80',
        tagline: 'Delivering verified, fast, and authoritative news to millions of listeners.',
        about: 'Jayda is the voice of truth at 93.5 Area FM. With razor-sharp reporting and deep journalistic integrity, she keeps the city informed.',
        bio: 'Investigative journalist and news anchor with extensive experience covering local politics, economics, and human interest stories.',
        birthday: 'Dec 05',
        onAirSince: '2018',
        location: 'Lagos, Nigeria',
        instagram: 'https://instagram.com/jayda_news',
        twitter: 'https://twitter.com/jayda_news',
        tiktok: 'https://tiktok.com/@jayda_news',
        gradientColors: [Color(0xFFB54700), Color(0xFF4A1800)],
        accentColor: Color(0xFFFF8A00),
      ),
      PresenterModel(
        id: 'pres_eddie',
        name: 'Eddie',
        showName: 'Producer',
        timeSlot: 'Behind the Scenes',
        days: 'Daily',
        category: 'Producers',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=500&q=80',
        tagline: 'Crafting the sonic identity and seamless production of your favourite shows.',
        about: 'Eddie is the mastermind behind the console. From high quality sound effects to show formatting, he keeps Area FM sounding world-class.',
        bio: 'Sound designer, audio engineer, and broadcast producer responsible for programming top-tier radio experiences.',
        birthday: 'Oct 30',
        onAirSince: '2015',
        location: 'Lagos, Nigeria',
        instagram: 'https://instagram.com/eddie_producer',
        twitter: 'https://twitter.com/eddie_producer',
        tiktok: 'https://tiktok.com/@eddie_producer',
        gradientColors: [Color(0xFF132F52), Color(0xFF0A1524)],
        accentColor: Color(0xFF60A5FA),
      ),
      PresenterModel(
        id: 'pres_bella',
        name: 'Bella',
        showName: 'Content Creator',
        timeSlot: 'Digital Team',
        days: 'Daily',
        category: 'Producers',
        isOnAir: false,
        image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=500&q=80',
        tagline: 'Amplifying on-air magic into viral digital content and podcasts.',
        about: 'Bella leads digital storytelling at 93.5 Area FM. She transforms studio moments into engaging videos, reels, and podcast series.',
        bio: 'Digital strategist, content producer, and media personality bridging radio broadcasting with modern social networks.',
        birthday: 'Feb 17',
        onAirSince: '2022',
        location: 'Lagos, Nigeria',
        instagram: 'https://instagram.com/bella_digital',
        twitter: 'https://twitter.com/bella_digital',
        tiktok: 'https://tiktok.com/@bella_digital',
        gradientColors: [Color(0xFFB84E10), Color(0xFF4C1D04)],
        accentColor: Color(0xFFFF7A1A),
      ),
    ];
  }

  Future<PresenterModel> getPresenterById(String id) async {
    final presenters = await getPresenters();
    return presenters.firstWhere((p) => p.id == id, orElse: () => presenters.first);
  }
}
